#!/bin/bash
RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
BLUE="\e[34m"
PURPLE="\e[35m"
LBLUE="\e[36m"
DEF="\e[0m"

echo `date` >>/tmp/vkl


/home/actions/vkl_other_nodes

sleep 20

servers="raid23"
for server in $servers
    do  
    sleep 1
	echo -e "${PURPLE}Execution on ${RED}${server}${DEF}:${GREEN}"
	/home/actions/powermodule.pl ${server} on &
    done

sleep 300

mount /common
mount /home

